export { default as DepartmentsPage } from './DepartmentsPage';
export { default as DesignationsPage } from './DesignationsPage';
export { default as EmployeesPage } from './EmployeesPage';
export { default as FormerEmployeesPage } from './FormerEmployeesPage';
export { default as HRDashboard } from './HRDashboard';
export { default as HRLeavePage } from './HRLeavePage';
export { default as HRProfilePage } from './HRProfilePage';
export { default as HRProjectsPage } from './HRProjectsPage';
export { default as ManagersPage } from './ManagersPage';
